config/routes.rb
Ecc::Application.routes.draw do

  root to: 'teams#index'

  resources :participants do
    collection do
      get :tags
      get :name_tags
    end
  end

  resources :teams do
    collection do
      get :tags
      get :name_tags
    end
  end
end

app/models/concerns/person.rb
# -*- encoding : utf-8 -*-
module Person
  extend ActiveSupport::Concern

  included do
    attr_accessible :address, :phone, :cel_phone, :church, :email, :health_obs, :name, :nickname
    validates_presence_of :name
    validates_format_of :name, with: /.*\s{1}da{1}\s{1}.*/, message: "verifique o formato, exemplo: Carlos da Clotilde"
    default_scope order(:name)
  end

  def wife_full_name
    "#{wife_name} do #{husband_name}"
  end

  def husband_full_name
    "#{husband_name} da #{wife_name}"
  end

  def wife_name
    "#{wife(nickname)} (#{wife(name)})"
  end

  def husband_name
    "#{husband(nickname)} (#{husband(name)})"
  end

  def husband(naming)
    if naming.present?
      naming.split(" da ")[0]
    else
      ""
    end
  end

  def wife(naming)
    if naming.present?
      naming.split(" da ")[1]
    else
      ""
    end
  end
end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id         :integer          not null, primary key
#  address    :string(255)
#  phone      :string(255)
#  cel_phone  :string(255)
#  email      :string(255)
#  church     :string(255)
#  couple     :string(255)
#  health_obs :text
#  children   :integer
#  name       :string(255)
#  full_name  :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  nickname   :string(255)
#

# -*- encoding : utf-8 -*-
class Participant < ActiveRecord::Base
  include Person
  attr_accessible :children, :couple, :full_name
  validates_presence_of :full_name, :couple
  validates_format_of :nickname, with: /[a-zA-Z]+\s{1}da{1}\s{1}[a-zA-Z]+/,
  message: "verifique o formato, exemplo: Tchuco da Tchuca", if: Proc.new { |p| p.nickname.present? }
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null, primary key
#  address    :string(255)
#  phone      :string(255)
#  cel_phone  :string(255)
#  email      :string(255)
#  church     :string(255)
#  health_obs :text
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# -*- encoding : utf-8 -*-
class Team < ActiveRecord::Base
  include Person

  def wife_full_name
    wife(name) + " do " + name.split(" da ")[0]
  end

  def husband_full_name
    name
  end
end

app/controllers/application_controller.rb
require 'yaml'

class ApplicationController < ActionController::Base
  before_filter :authenticate
  protect_from_forgery

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['ECCUSER'] && password == ENV['ECCPASSWORD']
    end
  end
end

app/controllers/participants_controller.rb
# -*- encoding : utf-8 -*-
class ParticipantsController < ApplicationController

  before_filter :load, only: [:show, :edit, :update, :destroy]
  before_filter :load_people, only: [:tags, :name_tags]

  def index
    @participants = Participant.scoped
  end

  def tags; end

  def name_tags; end

  def show; end

  def edit; end

  def update
    if @participant.update_attributes(params[:participant])
      redirect_to participants_path, notice: "Encontrista alterado com sucesso"
    else
      render action: "edit"
    end
  end

  def new
    @participant = Participant.new
  end

  def create
    @participant = Participant.new(params[:participant])
    if @participant.save
      redirect_to participants_path, notice: "Encontrista criado com sucesso"
    else
      render action: "new"
    end
  end

  def destroy
    @participant.destroy
    redirect_to participants_path, notice: "Encontrista excluído com sucesso"
  end

  protected
  def load
    @participant = Participant.find params[:id]
  end

  def load_people
    @people = params[:ids].present? ? Participant.where("id in (?)", params[:ids]) : Participant.scoped
  end
end

app/controllers/teams_controller.rb
# -*- encoding : utf-8 -*-
class TeamsController < ApplicationController

  before_filter :load, only: [:show, :edit, :update, :destroy]
  before_filter :load_people, only: [:tags, :name_tags]

  def index
    @teams = Team.scoped
  end

  def tags; end

  def name_tags; end

  def show; end

  def edit; end

  def update
    if @team.update_attributes(params[:team])
      redirect_to teams_path, notice: "Equipe alterada com sucesso"
    else
      render action: "edit"
    end
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    if @team.save
      redirect_to teams_path, notice: "Equipe criada com sucesso"
    else
      render action: "new"
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_path, notice: "Equipe excluída com sucesso"
  end

  protected
  def load
    @team = Team.find params[:id]
  end

  def load_people
    @people = params[:ids].present? ? Team.where("id in (?)", params[:ids]) : Team.scoped
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:message] ||= "Corrija os erros e tente novamente"
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, class: "error_explanation") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h3, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_name_tags.html.erb
<%= link_to_function "Imprimir", "window.print()", id: "printButton", class: "button small" %>
<div id="printable-name-tag">
  <div class="row">
    <% @people.each_with_index do |person, i| %>
      <div class="name_tag">
        <div>
          <%= image_tag("hearts.png") %>&nbsp;&nbsp;&nbsp;
          47º ECC - Maranata
        </div>
        <p><%= person.husband_full_name %></p>
      </div>
      <div class="name_tag">
        <div>
          <%= image_tag("hearts.png") %>&nbsp;&nbsp;&nbsp;
          47º ECC - Maranata
        </div>
        <p><%= person.wife_full_name %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Encontro de Casais com Cristo", participants_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li class="has-dropdown">
        <%= link_to "Encontristas", participants_path %>
        <ul class="dropdown">
          <li><%= link_to "Gerenciar", participants_path %></li>
          <li><%= link_to "Etiquetas", tags_participants_path %></li>
          <li><%= link_to "Crachás", name_tags_participants_path %></li>
          <li><a href="#">Dormitórios</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <%= link_to "Equipe", teams_path %>
        <ul class="dropdown">
          <li><%= link_to "Gerenciar", teams_path %></li>
          <li><%= link_to "Crachás", name_tags_teams_path %></li>
          <li><a href="#">Relação Lava-Louça</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <!-- <li><%#= link_to "Sair" %></li> -->
    </ul>
  </div>
</nav>

app/views/layouts/_tags.html.erb
<%= link_to_function "Imprimir", "window.print()", id: "printButton", class: "button small" %>
<div id="printable-tag">
  <div class="row">
    <% @people.each do |person| %>
        <div class="tag">
          <div><%= image_tag("hearts.png") %></div>
          <p><%= person.husband_full_name %></p>
        </div>
        <div class="tag">
          <div><%= image_tag("hearts.png") %></div>
          <p><%= person.wife_full_name %></p>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Encontro de Casais com Cristo" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <style type="text/css">

      @media print
      {
        .non-printable { display: none; }
        #printButton { display: none; }
        .row { font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; }
        #printable-tag .row { width: 1056px; margin: 35px 5px 0 0; }
        #printable-name-tag .row { width: 1056px; margin: 35px 5px 0 0; }

        /* TAGS */
        .tag {
          border: 1px solid;
          /*border-color: white;*/
          margin: 0 0 0 15px;
          width: 253px;
          height: 94px;
          float: left;
          page-break-inside: avoid;
        }
        .tag div {
          text-align: center;
          height: 10px;
          margin-top: 5px;
        }
        .tag p {
          text-align: center;
          /*padding: 5px;*/
          margin-top: 12px;
          font-size: 18px;
        }
        /* END OF TAGS */

        /* NAME TAGS */
        #printable-name-tag { display: block; }
        #printable-tag { display: block; }
        .name_tag {
          border: 1px solid;
          width: 240.00pt; /* Original size here is 336px */
          height: 135.00pt; /* Original size here is 192px */
          float: left;
          page-break-inside: avoid;
        }
        .name_tag div {
          font-size: 16px;
          height: 1px;
          margin: 15px 0 0 10px;
        }
        .name_tag p {
          text-align: center;
          margin-top: 45px;
          font-size: 30px;
          font-weight: bold;
        }
        /* END OF NAME TAGS */

        /* TABLE */
        .printable-table { display: block; }
        .printable-table table { border-collapse: collapse; }
        .printable-table table tbody td { border: 1px solid; }
        tr { page-break-inside:avoid; }
        td { page-break-inside:avoid; }
        /* END OF TABLE */
      }
    </style>
  </head>

  <body>
    <div class="non-printable">
      <%= render "layouts/navbar" %>

      <div class="row">
        <div class="small-12 columns"><%= yield %></div>
      </div>

    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_for @participant do |f| %>
  <%= error_messages_for @participant %>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :nickname, 'Apelido' %>
      <%= f.text_field :nickname %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :full_name, 'Nome Completo' %>
      <%= f.text_field :full_name %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :church, 'Igreja' %>
      <%= f.text_field :church %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :couple, 'Casal que convidou' %>
      <%= f.text_field :couple %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :health_obs, 'Obs. de Saúde' %>
      <%= f.text_area :health_obs %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :phone, 'Telefone' %>
      <%= f.text_field :phone %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :cel_phone, 'Celular' %>
      <%= f.text_field :cel_phone %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :children, 'Qtd. de filhos' %>
      <%= f.text_field :children %>
    </div>
  </div>

  <div class="row">
    <div class="large-4 columns">
      <%= f.label :address, 'Endereço' %>
      <%= f.text_area :address %>
    </div>
  </div>

  <div class="row collapse">
    <%= f.submit btn_text, class: "button radius" %>
    <%= link_to "Cancelar", participants_path, class: 'button secondary' %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editar Encontrista</h1>

<%= render 'form', btn_text: 'Alterar' %>

app/views/participants/index.html.erb
<h1 class="non-printable">Encontristas</h1>
<%= link_to "Adicionar", new_participant_path, class: "non-printable button small" %>
<%= link_to_function "Imprimir", "window.print()", id: "printButton", class: "button alert small" %>
<br/><br/>
<div class="printable-table">
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Casal Acomp.</th>
        <th>Igreja</th>
        <th>Tel.</th>
        <th>Saúde</th>
        <th class="non-printable"><th>
        <th class="non-printable"><th>
      </tr>
    </thead>
    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= link_to participant.husband_full_name, participant_path(participant) %></td>
          <td><%= participant.couple %></td>
          <td><%= participant.church %></td>
          <td><%= participant.phone %></td>
          <td><%= participant.health_obs %></td>
          <td class="non-printable"><%= link_to "Editar", edit_participant_path(participant) %></td>
          <td class="non-printable"><%= link_to 'Apagar', participant_path(participant), confirm: 'Tem certeza?', method: :delete %></td>
          <td class="non-printable"><%= link_to 'Crachá', name_tags_participants_path(ids: participant.id) %></td>
          <td class="non-printable"><%= link_to 'Etiqueta', tags_participants_path(ids: participant.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/participants/name_tags.html.erb
<%= render "layouts/name_tags" %>

app/views/participants/new.html.erb
<h1>Novo Encontrista</h1>

<%= render 'form', btn_text: 'Criar' %>

app/views/participants/show.html.erb
<h1><%= @participant.name %></h1>
<br/>
<p>
  <b>Nome Completo:</b>
  <%= @participant.full_name %>
</p>
<p>
  <b>Casal que convidou:</b>
  <%= @participant.couple %>
</p>
<p>
  <b>Igreja:</b>
  <%= @participant.church %>
</p>
<p>
  <b>Filhos:</b>
  <%= @participant.children %>
</p>
<p>
  <b>Telefone:</b>
  <%= @participant.phone %>
</p>
<p>
  <b>Celular:</b>
  <%= @participant.cel_phone %>
</p>
<p>
  <b>Email:</b>
  <%= @participant.email %>
</p>
<p>
  <b>Endereço:</b>
  <%= @participant.address %>
</p>
<p>
  <b>Obs. de Saúde:</b>
  <%= @participant.health_obs %>
</p>
<br/>
<%= link_to "Editar", edit_participant_path(@participant), class: "button radius" %>
<%= link_to "Voltar", participants_path, class: 'button secondary' %>

app/views/participants/tags.html.erb
<%= render "layouts/tags" %>